name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: routeros-pyscript

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lowercase Owner
        id: lowercase
        run: |
          echo "OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.OWNER }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            BUILDKIT_INLINE_CACHE=1
          outputs: type=image,name=${{ env.REGISTRY }}/${{ steps.lowercase.outputs.OWNER }}/${{ env.IMAGE_NAME }},name-only=true
      
      - name: Display image size
        run: |
          echo "正在拉取构建的镜像..."
          docker pull ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.OWNER }}/${{ env.IMAGE_NAME }}:latest
          echo "镜像大小信息:"
          docker images ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.OWNER }}/${{ env.IMAGE_NAME }}:latest --format "{{.Repository}}:{{.Tag}} - {{.Size}}"
          echo "详细信息:"
          docker image inspect ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.OWNER }}/${{ env.IMAGE_NAME }}:latest --format '{{.Size}} bytes (约 {{div .Size 1048576}} MB)'
